config/routes.rb
Rails.application.routes.draw do
  # get "home/index"
  # namespace :admin do
  #   get "users/index"
  # end
  # resources :daily_sales
  # resources :products
  # resources :categories
  # devise_for :users

  devise_for :users
  root 'home#index'

  resources :categories
  resources :products
  resources :daily_sales

  namespace :admin do
    resources :users, only: [:index] do
      member do
        patch :update_role
      end
    end
  end

  get 'admin/dashboard', to: 'dashboards#admin', as: 'admin_dashboard'
  get 'seller/dashboard', to: 'dashboards#seller', as: 'seller_dashboard'
  post 'admin/users/invite', to: 'admin/users#invite', as: 'invite_admin_users'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <% alert_type = case type.to_sym
                  when :notice then "success"
                  when :alert, :error then "error"
                  else type
                  end %>
  
  <div class="fixed inset-x-0 top-0 flex items-center justify-center px-4 py-3 pointer-events-none sm:p-6 sm:items-start sm:justify-end z-50">
    <div data-controller="flash" data-transition-enter-from="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" data-transition-enter-to="opacity-100 translate-y-0 sm:scale-100" data-transition-leave-from="opacity-100 translate-y-0 sm:scale-100" data-transition-leave-to="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95" class="max-w-sm w-full bg-<%= alert_type == 'error' ? 'red' : 'green' %>-50 shadow-lg rounded-lg pointer-events-auto">
      <div class="rounded-lg shadow-xs overflow-hidden">
        <div class="p-4">
          <div class="flex items-start">
            <div class="flex-shrink-0">
              <svg class="h-5 w-5 text-<%= alert_type == 'error' ? 'red' : 'green' %>-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                <% if alert_type == 'error' %>
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                <% else %>
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                <% end %>
              </svg>
            </div>
            <div class="ml-3 w-0 flex-1 pt-0.5">
              <p class="text-sm font-medium text-<%= alert_type == 'error' ? 'red' : 'green' %>-800">
                <%= message %>
              </p>
            </div>
            <div class="ml-4 flex-shrink-0 flex">
              <button class="inline-flex text-<%= alert_type == 'error' ? 'red' : 'green' %>-400 hover:text-<%= alert_type == 'error' ? 'red' : 'green' %>-500 focus:outline-none" data-action="flash#dismiss">
                <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
<nav class="bg-red-800">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex items-center align-items-center gap-2">
          <div>
            <%= image_tag "nita_logo.png", alt: "Nita Nation Logo", class: "h-8 w-8" %>
          </div>
            <div class="text-white font-bold text-xl">
              Nita Nation
            </div>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <%= link_to "Dashboard", current_user.admin? ? admin_dashboard_path : seller_dashboard_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
            <% if current_user.admin? %>
              <%= link_to "Products", products_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to "Categories", categories_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to "Users", admin_users_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
            <% end %>
            <%= link_to "Daily Sales", daily_sales_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
          </div>
        </div>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <div class="ml-3 relative">
            <div>
              <button type="button" class="max-w-xs bg-red-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-red-800 focus:ring-white" id="user-menu" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <span class="text-white px-3 py-2 rounded-md text-sm font-medium"><%= current_user.email %></span>
              </button>
            </div>
          </div>
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "block w-full text-left px-4 py-2 text-yellow-300 hover:cursor-pointer hover:bg-red-700 hover:text-yellow-100 transition duration-200" %>
        </div>
      </div>
    </div>
  </div>
</nav>
<% end %>

app/views/layouts/_navbar2.html.erb
<% if user_signed_in? %>
<nav class="bg-red-800" x-data="{ isOpen: false }">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex items-center align-items-center gap-2">
          <div>
            <%= image_tag "nita_logo.png", alt: "Nita Nation Logo", class: "h-8 w-8" %>
          </div>
          <div class="text-white font-bold text-xl">
            Nita Nation
          </div>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <%= link_to "Dashboard", current_user.admin? ? admin_dashboard_path : seller_dashboard_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
            <% if current_user.admin? %>
              <%= link_to "Products", products_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to "Categories", categories_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to "Users", admin_users_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
            <% end %>
            <%= link_to "Daily Sales", daily_sales_path, class: "text-white hover:bg-red-700 px-3 py-2 rounded-md text-sm font-medium" %>
          </div>
        </div>
      </div>
      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <div class="ml-3 relative">
            <div>
              <button type="button" class="max-w-xs bg-red-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-red-800 focus:ring-white" id="user-menu" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <span class="text-white px-3 py-2 rounded-md text-sm font-medium"><%= current_user.email %></span>
              </button>
            </div>
          </div>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "block w-full text-left px-4 py-2 text-yellow-300 hover:cursor-pointer hover:bg-red-700 hover:text-yellow-100 transition duration-200" %>
        </div>
      </div>
      
      <!-- Mobile menu button -->
      <div class="-mr-2 flex md:hidden">
        <button @click="isOpen = !isOpen" type="button" class="bg-red-800 inline-flex items-center justify-center p-2 rounded-md text-white hover:text-white hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-red-800 focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!-- Hamburger icon -->
          <svg :class="{'hidden': isOpen, 'block': !isOpen}" class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!-- Close icon -->
          <svg :class="{'hidden': !isOpen, 'block': isOpen}" class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu -->
  <div x-show="isOpen" class="md:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
      <%= link_to "Dashboard", current_user.admin? ? admin_dashboard_path : seller_dashboard_path, class: "text-white hover:bg-red-700 block px-3 py-2 rounded-md text-base font-medium" %>
      <% if current_user.admin? %>
        <%= link_to "Products", products_path, class: "text-white hover:bg-red-700 block px-3 py-2 rounded-md text-base font-medium" %>
        <%= link_to "Categories", categories_path, class: "text-white hover:bg-red-700 block px-3 py-2 rounded-md text-base font-medium" %>
        <%= link_to "Users", admin_users_path, class: "text-white hover:bg-red-700 block px-3 py-2 rounded-md text-base font-medium" %>
      <% end %>
      <%= link_to "Daily Sales", daily_sales_path, class: "text-white hover:bg-red-700 block px-3 py-2 rounded-md text-base font-medium" %>
    </div>
    <div class="pt-4 pb-3 border-t border-red-700">
      <div class="flex items-center px-5">
        <div class="flex-shrink-0">
          <span class="text-white"><%= current_user.email %></span>
        </div>
      </div>
      <div class="mt-3 px-2 space-y-1">
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "block w-full text-left px-3 py-2 text-yellow-300 hover:cursor-pointer hover:bg-red-700 hover:text-yellow-100 transition duration-200 rounded-md text-base font-medium" %>
      </div>
    </div>
  </div>
</nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Nita" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar2" %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>